(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[133,360,69,59],[0,252,202,106],[0,360,131,69],[204,252,85,140],[0,0,300,250]]}
];


// symbols:



(lib.cookiebottomleft = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.cookiebottomright = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.cookietopleft = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.cookie = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.table = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.whitesquare = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A41UyMAAAgpjMAxrAAAMAAAApjg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.whitesquare, new cjs.Rectangle(-158.9,-133,318,266), null);


(lib.table_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.table();
	this.instance.parent = this;
	this.instance.setTransform(-150,-125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.table_1, new cjs.Rectangle(-150,-125,300,250), null);


(lib.sweetinspiration = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AAXBWQgIgDAAgGQAAgHAIgDIAHgDQAEgCABgIQACgIAAgSQAAg2gHgOQgHgOgSAAQgJAAgIAGQgIAFgFAKQgEAHgBANQgCANAAAiQAAARACAGQABAFAEACIAGADQAJADAAAHQAAAGgIADQgJADgWgBQgbABgIgDQgJgDAAgHQAAgHAJgCIAEgCQAEgDACgFQACgGAAgNIAAgNIAAgNIAAgRQAAgcgCgHQgBgJgDgCIgIgDQgLgDAAgGQAAgDADgDQAEgEAHgDIAZgIIASgDQAFAAACADQACADAAAFIAAALIAAACIABABIABgBIABAAIAEgDIAEgEQASgRAVAAQANgBALAGQAMAFAIAKQAIAJADANQADANAAAcIAAAWIAAAMIAAAKQAAAMACAFQACAFAEADIAEACQAJACAAAHQAAAHgIADQgIACgbAAQgYABgIgDg");
	this.shape.setTransform(77.9,22.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("Ag+BBQgZgaAAgmQAAgmAagaQAagaAmAAQAlAAAYAYQAYAYAAAmQAAAngaAbQgZAbglAAQgmAAgYgZgAgggzQgLAOAAAXQAAAiAPAXQAOAXAUAAQARAAALgOQAKgPAAgXQAAghgOgXQgPgXgUAAQgRAAgKAOg");
	this.shape_1.setTransform(57.9,23);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AgeB8QgJgDABgIQgBgGAJgDIAEgCQAFgCACgGQABgGAAgNIAAgMIAAgNIAAgSQAAgcgBgHQgBgIgEgCIgIgDQgLgDAAgGQAAgEAEgDQADgDAIgDIAagIIARgEQAFAAABAEQADADAAAIIAAAKIgBAIIgBArIAAABIgBArQAAAQACAHQABAHAEACIAHACQAJAEAAAGQAAAHgJADQgIACgXAAQgZAAgJgCgAgVhWQgHgGAAgJQAAgKAIgHQAIgHAMAAQAKAAAIAGQAHAHAAAJQAAAJgIAHQgIAHgLAAQgLAAgIgGg");
	this.shape_2.setTransform(43.3,19.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AgIBoQgJgDgGgGQgGgFgDgKQgCgJAAgaIAAhcIgQAAIgFgBIgCgFIAAgEQAAgGASgPIAHgGIAHgGQASgQAHAAIAEACQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABIAAAgIAnAAQAEAAACACQABABAAAFIAAAEQAAAFgBACQgCACgEAAIgkAAIgDABIgBAEIAABVQAAAXAEAFQAEAGAKAAQAGAAAIgDIAMgDQAEAAACADQADACAAADQAAAKgPAJQgPAJgSAAQgKAAgIgDg");
	this.shape_3.setTransform(32.4,21.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AAfBRIgKgJIgHAEQgUAOgWAAQgZAAgQgOQgPgPAAgYQgBgbAVgPQAUgPAkAAQAIAAAFACQAEADAAAGQAAAKgMAAQgQAAgLAIQgLAIAAAPQABAOAIAIQAKAIAPAAQAQAAAHgHQAHgIAAgSIAAhBQAAgPgGgIQgHgIgLAAQgJAAgHADQgIAEgGAIIgEAEQgKAOgMAAQgHAAgEgFQgEgEAAgIQAAgQAUgLQAUgLAgAAQASAAAOAFQAOAFAHAKQAFAGADALQABAKAAAZIAAA3QABAKABAFQACAEAEABIAEACQAMADAAAGQAAAIgMAHQgLAGgQAAQgHAAgJgJg");
	this.shape_4.setTransform(17.2,23);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("Ag0BWQgIgDAAgHQAAgHAIgCIAFgCQAEgDACgFQACgGAAgNIAAgNIAAgNIAAgKQAAgggCgJQgBgJgEgDIgIgDQgKgDAAgGQAAgEADgDQADgDAIgDIAXgIIAQgCQAIAAADAXIAAAEIABAAQAJgOAJgHQAKgIAKABQAMgBAHAIQAHAHAAAMQAAAMgFAHQgGAHgKAAIgIgCIgIgFIgEgGQgBgFgCAAQgMAAgFAQQgEARAAA0QAAAPABAHQACAIAFACIAHACQAKADAAAIQAAAGgJADQgKADgXgBQgaABgJgDg");
	this.shape_5.setTransform(1.5,22.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AgeB8QgIgDgBgIQABgGAIgDIAEgCQAEgCACgGQACgGAAgNIAAgMIAAgNIAAgSQAAgcgCgHQgBgIgDgCIgIgDQgLgDABgGQAAgEADgDQADgDAHgDIAagIIASgEQAFAAACAEQABADAAAIIAAAKIAAAIIgBArIAAABIgBArQAAAQACAHQABAHAEACIAGACQAKAEgBAGQAAAHgIADQgJACgWAAQgaAAgIgCgAgVhWQgHgGAAgJQAAgKAIgHQAIgHAMAAQAKAAAHAGQAIAHAAAJQAAAJgIAHQgIAHgMAAQgLAAgHgGg");
	this.shape_6.setTransform(-10.4,19.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AhTB2QgJgDAAgHQAAgGAHgDIAJgEQAEgEABgOQABgNAAgrIAAgcQAAgugBgOQgCgOgEgCIgIgDQgKgDAAgGQAAgEADgDQADgDAHgDIAYgIQAMgDAGAAQAFAAACADQACADAAAGIAAAIIAAADIABACIAHgFIAGgFQALgIAJgEQAKgEAKAAQAgAAAVAYQAUAXAAAmQAAAogXAbQgXAbgjAAQgPAAgFgEQgGgFAAgHQAAgDADgDQADgDAFAAIAEABIAGABQATAAAMgQQALgQAAgaQAAgegMgSQgNgSgTAAQgSAAgKAKQgLAKAAAaIAABtIABASQABAGACADQADACAHACIAHADIAEADIABAFQAAAGgKADQgKADgZAAQgZAAgIgDg");
	this.shape_7.setTransform(-26,26.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AgMBaIgTgEIgFAEIgFABIgEgBIgDgDQgGgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJAAQALAAAIgFQAGgGAAgJQAAgPgcgOIgKgFQgbgNgJgLQgKgLAAgRQAAgWAQgOQAPgOAZAAIALAAIANADIAIgEIAFgBQAJAAAIAOQAIANAAAPQAAAGgCAEQgDAEgFAAQgEAAgEgEQgEgDgGgIQgFgLgHgFQgIgDgJAAQgKgBgFAGQgHAFAAAKQABAIAGAGQAGAGAUAKIACACQAxAWAAAcQAAAZgSAQQgTAQgcAAg");
	this.shape_8.setTransform(-43.3,23);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006F46").s().p("AAXBWQgIgDAAgGQAAgHAIgDIAHgDQAEgCABgIQACgIAAgSQAAg2gHgOQgHgOgSAAQgJAAgIAGQgIAFgFAKQgEAHgBANQgCANAAAiQAAARACAGQABAFAEACIAGADQAJADAAAHQAAAGgIADQgJADgWgBQgbABgIgDQgJgDAAgHQAAgHAJgCIAEgCQAEgDACgFQACgGAAgNIAAgNIAAgNIAAgRQAAgcgCgHQgBgJgDgCIgIgDQgLgDAAgGQAAgDADgDQAEgEAHgDIAZgIIASgDQAFAAACADQACADAAAFIAAALIAAACIABABIABgBIABAAIAEgDIAEgEQASgRAVAAQANgBALAGQAMAFAIAKQAIAJADANQADANAAAcIAAAWIAAAMIAAAKQAAAMACAFQACAFAEADIAEACQAJACAAAHQAAAHgIADQgIACgbAAQgYABgIgDg");
	this.shape_9.setTransform(-61,22.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006F46").s().p("AgkB6QgJgDAAgIQAAgHAKgEIAIgEQAEgCABgVQACgVAAg1IgChBQgBgagCgDQgCgCgJgEQgJgEAAgHQAAgGAHgDQAIgDAeAAQAfAAAIADQAHACAAAHQAAAHgKAEIgIAEQgDADgCARIgBA5IABBRQABAfACADQACACAJAEQAJADAAAHQAAAIgJADQgKADgbAAQgaAAgKgDg");
	this.shape_10.setTransform(-76.8,19.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006F46").s().p("AgIBoQgJgDgGgGQgGgFgDgKQgCgJAAgaIAAhcIgQAAIgFgBIgCgFIAAgEQAAgGASgPIAHgGIAHgGQASgQAHAAIAEACQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABIAAAgIAnAAQAEAAACACQABABAAAFIAAAEQAAAFgBACQgCACgEAAIgkAAIgDABIgBAEIAABVQAAAXAEAFQAEAGAKAAQAGAAAIgDIAMgDQAEAAACADQADACAAADQAAAKgPAJQgPAJgSAAQgKAAgIgDg");
	this.shape_11.setTransform(8.8,-16.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006F46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_12.setTransform(-6.5,-15);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006F46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_13.setTransform(-24.8,-15);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006F46").s().p("AAKATIgUg2QgKgYgIgEIgGgCQgJgEAAgHQAAgHAJgCQAIgDAbAAQAXAAAJADQAJACgBAHIgBAGIgDADIgGACQgHADAAAEIAEALIANAkIAPAhQAEAIADAAQACAAADgFIAIgPIASgrQAHgRgBgFIgBgHIgEgDIgEgCQgJgDAAgGQAAgHAJgCQAHgDAVAAQASAAAIADQAIACAAAHQgBAHgIADIgHACQgHAEgRAkIgDAIIgHAQQgnBZgMAAQgLAAgfhGgAhlAKIgFgLIgLgdQgLgdgIgEIgGgCQgKgEABgHQgBgHAKgCQAIgDAcAAQAYAAAIADQAJACgBAHIgBAGIgDADIgGACQgGADAAAEIADAOIANAhIAPAgQAFAJACAAQAFAAAFgLIAFgMIAEgFQACgCAEAAQAEAAADACQACADAAAEQAAAFgFAJQgRAogJANQgHANgGAAQgNAAgihPg");
	this.shape_14.setTransform(-47.8,-14.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006F46").s().p("AgqB8QgTgEgNgHQgGgEgFgPQgEgPAAgTQAAgIADgEQADgEAFAAQAIAAAJAPIAEAHQALAUANAIQANAJASAAQASAAANgLQANgLAAgQQAAgYgygXIgGgDQgqgRgNgPQgOgQAAgYQAAgfAXgUQAXgUAkAAIAUACIAYAFIAHgEIAGgCQAEAAADADQAEACADAHQAGALAEALQADALAAAJQAAAFgDAEQgDADgEAAQgKAAgIgNIgDgDQgKgNgLgFQgMgHgOAAQgTAAgLAJQgLAJAAAQQAAAOAJAKQAKAIAkAQIAHAEQAfANAOALQAJAJAFAMQAFAMAAANQAAAkgYATQgZAUgrAAQgVAAgTgFg");
	this.shape_15.setTransform(-72.4,-18.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.sweetinspiration, new cjs.Rectangle(-84.3,-41.5,174.8,83.1), null);


(lib.square = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#99CC33").ss(1,1,1).p("A3UxxMAupAAAMAAAAjjMgupAAAg");
	this.shape.setTransform(0.2,0.5,1.003,1.096);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("A3URxMAAAgjhMAupAAAMAAAAjhg");
	this.shape_1.setTransform(0.2,0.5,1.003,1.096);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#99CC33").ss(1,1,1).p("AAASIMAAAgkP");
	this.shape_2.setTransform(-149.9,-9.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150.9,-126.1,301.9,252.4);


(lib.partyreadyrecipes = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AgMBaIgTgEIgFAEIgGABIgDgBIgDgDQgGgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJAAQAMAAAGgFQAHgGAAgJQAAgPgcgOIgKgFQgbgNgJgLQgKgLAAgRQAAgWAPgOQAQgOAaAAIAKAAIANADIAIgEIAFgBQAJAAAIAOQAIANAAAPQAAAGgCAEQgEAEgEAAQgEAAgEgEQgEgDgFgIQgHgLgHgFQgGgDgKAAQgKgBgFAGQgHAFAAAKQABAIAGAGQAGAGAVAKIABACQAxAWAAAcQAAAZgTAQQgSAQgcAAg");
	this.shape.setTransform(23.1,23);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_1.setTransform(6.6,23);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AhTB2QgJgDAAgHQAAgGAHgDIAJgEQAEgEABgOQABgNAAgrIAAgcQAAgugBgOQgCgOgEgCIgIgDQgKgDAAgGQAAgEADgDQADgDAHgDIAYgIQAMgDAGAAQAFAAACADQACADAAAGIAAAIIAAADIABACIAHgFIAGgFQALgIAJgEQAKgEAKAAQAgAAAVAYQAUAXAAAmQAAAogXAbQgXAbgjAAQgPAAgFgEQgGgFAAgHQAAgDADgDQADgDAFAAIAEABIAGABQATAAAMgQQALgQAAgaQAAgegMgSQgNgSgTAAQgSAAgKAKQgLAKAAAaIAABtIABASQABAGACADQADACAHACIAHADIAEADIABAFQAAAGgKADQgKADgZAAQgZAAgIgDg");
	this.shape_2.setTransform(-13.3,26.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AgeB8QgJgDABgIQgBgGAJgDIAEgCQAFgCACgGQACgGAAgNIgBgMIAAgNIAAgSQAAgcgBgHQgBgIgEgCIgIgDQgLgDAAgGQAAgEADgDQAEgDAIgDIAagIIARgEQAEAAACAEQACADABAIIAAAKIgBAIIgBArIAAABIgBArQAAAQABAHQACAHAEACIAHACQAIAEABAGQAAAHgJADQgIACgXAAQgZAAgJgCgAgVhWQgHgGAAgJQAAgKAIgHQAIgHAMAAQAKAAAIAGQAHAHAAAJQAAAJgIAHQgIAHgLAAQgLAAgIgGg");
	this.shape_3.setTransform(-27.9,19.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("Ag2BBQgZgZAAglQAAgnAagbQAagaAmAAQAdAAAUAPQAUAOAAAUQAAAIgGAGQgGAFgIAAQgJAAgFgFQgGgEgGgOQgFgMgHgFQgGgFgLAAQgTAAgLAPQgLAPAAAaQAAAeAPAUQAQATAYAAQAJAAAIgCQAHgDAHgEIAHgFQAJgHAFAAQAEAAACACQACACAAADQAAAFgEAGQgDAGgGAFQgOAMgOAFQgPAGgRAAQgkAAgYgZg");
	this.shape_4.setTransform(-41.6,23);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_5.setTransform(-59.7,23);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AAlBWQgQg3gNgLQgLgLgRAAQgOAAAAgLQAAgLALAAQAcAAAOgLQAOgLAAgYQAAgWgOgMQgOgLgaAAQgOAAgEABQgGACgCAFIgBAPIgBAjIAABMIABA0QABAMADACIAIAEQAKAEAAAHQAAAHgJADQgJADgcAAQgbAAgKgDQgJgDAAgHQAAgHAKgEIAIgEQAEgDACgVQABgUAAg2IgBhBQgCgZgCgDQgCgDgJgEQgJgDAAgHQAAgGAFgDQAGgDAKAAIAmAAIAjgBIAbgBQAmAAATAQQAUARAAAeQAAAXgNAQQgNARgYAHIAAACQASADAMAMQAKALAIAcIAEARQAIAbAJAAIAGAAIAGgBQADAAACADQADADAAADQAAAIgKAFQgJAGgRAAQgiAAgMgpg");
	this.shape_6.setTransform(-80.7,19.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AhPByQgIgHAAgLQAAgIAGgHQAGgGAIAAIAIABIAFAEIAFAHQAEAHAEAAQAJAAAJgNQAJgNAAgNQAAgPgMgcIgCgEIgcg8IgQghQgDgGgKgFIAAAAQgGgCgCgCQgCgDAAgEQAAgHAJgDQAJgDAZAAQAaAAAIADQAIACAAAHIgBAGIgDADIgGADQgHACAAADIAEANIAOAjIANAgQAFAJACAAQACAAAEgJIALgbIANgiQAEgMAAgFQAAgFgKgFQgKgGAAgEQAAgGAIgDQAIgCAUAAQAVAAAHADQAHACAAAHQAAAHgKACIgHACQgKAGgLAdIgFANIgWA3QgcBIgSAWQgSAVgZAAQgNAAgIgHg");
	this.shape_7.setTransform(90.9,-11.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AhLBoQgUgXAAglQAAgqAXgaQAXgbAlABIAMABQAFACADAEQADADAAAEQAAAKgLAAIgFgBIgEAAQgTAAgMAQQgLAOAAAcQAAAdAMASQANASATAAQASABAKgLQAKgKAAgTIAAgvIAAhPQAAgMgDgFQgCgEgGgDIgFgBQgLgEAAgFQAAgFAEgEQAFgDANgFIATgFIAQgCQAGAAADAEQACACAAAJIAAAIIgCBqIABBJQABAQADACIAMAEQAJACAAAGQAAAIgZAIIgRAFIgNACQgFAAgCgEQgCgCAAgGIAAgJIgBgDIgBgBIgFAEIgIAFQgKAJgJADQgKAEgKAAQghAAgUgYg");
	this.shape_8.setTransform(72.5,-18.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006F46").s().p("AAfBRIgKgJIgHAEQgVAOgVAAQgZAAgQgOQgPgPgBgYQAAgbAVgPQAUgPAkAAQAIAAAEACQAFADAAAGQAAAKgMAAQgQAAgLAIQgLAIAAAPQABAOAIAIQAJAIAQAAQAQAAAHgHQAHgIAAgSIAAhBQAAgPgGgIQgHgIgLAAQgJAAgHADQgIAEgGAIIgEAEQgKAOgMAAQgHAAgEgFQgEgEAAgIQAAgQAUgLQAUgLAgAAQASAAANAFQAOAFAIAKQAFAGADALQACAKAAAZIAAA3QgBAKACAFQACAEAEABIAEACQALADAAAGQABAIgMAHQgLAGgQAAQgHAAgJgJg");
	this.shape_9.setTransform(52.6,-15);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006F46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_10.setTransform(34,-15);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006F46").s().p("AAlBWQgQg3gNgLQgLgLgRAAQgOAAAAgLQAAgLALAAQAdAAAOgLQANgLAAgYQAAgWgOgMQgOgLgaAAQgOAAgEABQgGACgCAFIgBAPIgBAjIAABMIABA0QABAMADACIAIAEQALAEgBAHQABAHgKADQgKADgbAAQgbAAgKgDQgJgDAAgHQAAgHAKgEIAIgEQAEgDACgVQABgUAAg2IgBhBQgCgZgCgDQgCgDgJgEQgJgDAAgHQAAgGAFgDQAGgDAKAAIAmAAIAjgBIAbgBQAmAAATAQQAVARgBAeQAAAXgNAQQgNARgYAHIAAACQATADAKAMQALALAIAcIAFARQAHAbAJAAIAFAAIAHgBQADAAACADQADADAAADQAAAIgJAFQgLAGgQAAQgiAAgMgpg");
	this.shape_11.setTransform(13,-18.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006F46").s().p("AghASQgGAAgCgCQgCgCAAgFIABgIIAEgJQACgFADgCQACgBAIAAIAIAAIAPAAIAdgBIAFAAQAFAAADACQACACAAAEQAAAKgFAIQgGAIgIAAIgIAAIgJAAIgmABIgDAAg");
	this.shape_12.setTransform(-5.7,-15.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006F46").s().p("AhPByQgIgHAAgLQAAgIAGgHQAGgGAIAAIAIABIAFAEIAFAHQAEAHAEAAQAJAAAJgNQAJgNAAgNQAAgPgMgcIgCgEIgcg8IgQghQgDgGgKgFIAAAAQgGgCgCgCQgCgDAAgEQAAgHAJgDQAJgDAZAAQAaAAAIADQAIACAAAHIgBAGIgDADIgGADQgHACAAADIAEANIAOAjIANAgQAFAJACAAQACAAAEgJIALgbIANgiQAEgMAAgFQAAgFgKgFQgKgGAAgEQAAgGAIgDQAIgCAUAAQAVAAAHADQAHACAAAHQAAAHgKACIgHACQgKAGgLAdIgFANIgWA3QgcBIgSAWQgSAVgZAAQgNAAgIgHg");
	this.shape_13.setTransform(-20.1,-11.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006F46").s().p("AgIBoQgJgDgGgGQgGgFgDgKQgCgJAAgaIAAhcIgQAAIgFgBIgCgFIAAgEQAAgGASgPIAHgGIAHgGQASgQAHAAIAEACQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABIAAAgIAnAAQAEAAACACQABABAAAFIAAAEQAAAFgBACQgCACgEAAIgkAAIgDABIgBAEIAABVQAAAXAEAFQAEAGAKAAQAGAAAIgDIAMgDQAEAAACADQADACAAADQAAAKgPAJQgPAJgSAAQgKAAgIgDg");
	this.shape_14.setTransform(-34.9,-16.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006F46").s().p("Ag0BWQgIgDAAgIQAAgFAIgEIAFgBQAEgDACgFQACgHAAgMIAAgNIAAgNIAAgKQAAgggCgJQgBgJgEgDIgIgDQgKgDAAgGQAAgEADgDQADgDAIgDIAXgIIAQgCQAIgBADAYIAAAEIABAAQAJgOAJgHQAKgHAKAAQAMAAAHAHQAHAHAAAMQAAAMgFAHQgGAHgKAAIgIgCIgIgFIgEgHQgBgEgCAAQgMAAgFAQQgEARAAAzQAAAPABAJQACAHAFACIAHACQAKAEAAAGQAAAHgJADQgKACgXAAQgaAAgJgCg");
	this.shape_15.setTransform(-47.3,-15.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006F46").s().p("AAfBRIgKgJIgHAEQgVAOgVAAQgZAAgQgOQgQgPAAgYQABgbATgPQAVgPAkAAQAIAAAEACQAFADAAAGQAAAKgMAAQgRAAgKAIQgLAIAAAPQAAAOAJAIQAKAIAPAAQAQAAAHgHQAHgIAAgSIAAhBQAAgPgHgIQgGgIgMAAQgIAAgHADQgHAEgHAIIgEAEQgKAOgMAAQgHAAgEgFQgEgEAAgIQAAgQAUgLQAUgLAfAAQATAAANAFQAOAFAIAKQAFAGACALQACAKABAZIAAA3QAAAKABAFQACAEADABIAGACQALADgBAGQAAAIgLAHQgMAGgPAAQgIAAgIgJg");
	this.shape_16.setTransform(-63.3,-15);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006F46").s().p("AhZB6QgKgCAAgIQAAgHALgEIAHgEQAEgDACgUQABgVAAg2IgBhBQgCgZgCgDQgCgCgJgFQgJgDAAgHQAAgGAFgDQAGgDAKAAIASAAIAUAAIAjAAIAbgBQAnAAATAQQAUAQAAAiQAAAkgYATQgYASguAAQgRAAAAgLQAAgNAPAAQAVABAOgMQANgLAAgaQAAgYgNgLQgOgLgcAAQgMAAgFACQgGACgBAFIgCAQIgBAkIAABLIABAxQABANADACIAIAEQALAEAAAHQAAAIgKACQgJADgcAAQgbAAgJgDg");
	this.shape_17.setTransform(-82.7,-18.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.partyreadyrecipes, new cjs.Rectangle(-95.5,-41.5,197.1,83.1), null);


(lib.ordernow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOAzQgHgDgEgEQgEgFgDgGQgCgHAAgIQAAgHACgGQADgFAEgFQAEgFAHgDQAFgCAIAAQAHAAAHAEQAFADAEAEIAAgxIANAAIAABpIgNAAIAAgKQgDAFgHAEQgGADgHAAQgHAAgGgDgAgIgCQgEABgDADIgEAIQgBAEgBAEQABAFABAFIAEAIIAHAEQAEADAFAAQAEAAAFgCQAEgCADgDIAFgIIABgJQAAgFgBgEIgFgIQgDgDgEgBQgFgDgEAAQgFAAgEADg");
	this.shape.setTransform(34.7,-1.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgLAhQgHgDgEgFQgEgFgDgFQgDgHAAgIQAAgHADgGQACgGAFgGQAEgEAHgDQAGgCAGAAQAHAAAHACQAGACAEAFQAEAEACAHQACAGAAAIIAAABIAAACIg0AAQAAAFACADQACAEADADQADADAEACQAEABADAAQAGAAAGgDQAEgDAEgEIAJAHQgGAHgHAEIgIACIgIABQgHAAgGgCgAAUgFIgCgHQAAgEgDgCQgCgDgEgCQgDgBgFAAQgDAAgEABQgEACgCADQgDACgCAEQgCADAAAEIAnAAIAAAAg");
	this.shape_1.setTransform(26.3,0.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgSAiIAAgzIAAgHIAAgIIAMAAIAAAGIABAGQADgGAEgDIAGgEIAGAAIAFAAIAAANIgGgBQgFAAgDACIgFAEQgDADgBAEIgBAIIAAAig");
	this.shape_2.setTransform(20,0.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgGAxIAAhBIAMAAIAABBgAgFgiQgDgDAAgDQAAgEADgCQACgCADgBQADABADACQADACAAAEQAAAEgDACQgDADgDgBQgDABgCgDg");
	this.shape_3.setTransform(15,-1.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgiAzIAAhjIAMAAIAAAKIABAAQADgFAGgDQAHgEAHAAQAHAAAGADQAGACAFAFQAEAFADAGQACAHAAAHQAAAHgCAHQgDAFgEAFQgEAFgHACQgGADgHAAQgHAAgGgDQgGgDgEgGIAAAAIAAAsgAgJglQgEACgDADQgDAEgBAEQgCAEAAAFQAAAFACAEQABAEADADQADADAEACQAEACAFAAQAFAAAEgCIAHgFQADgDABgEIABgJIgBgJQgBgEgDgEQgDgDgEgCQgEgCgFAAQgFAAgEACg");
	this.shape_4.setTransform(8.8,2.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgOAgQgHgDgFgGIAKgIQACAEAFACQAFADAEAAIAFAAIAEgCIADgDQABAAAAgBQAAAAAAgBQABAAAAgBQAAgBAAAAQAAgFgFgCIgMgFIgHgCIgGgCQgDgCgBgDQgCgDAAgFQAAgFACgEQACgEAEgCQADgDAFgBIAIgBQAHAAAHACQAGAEAEAEIgJAIQgCgDgEgCQgEgDgFAAIgEAAIgEACIgDADIgBAEQAAAEAEACIAKAEIAJADIAHACQADACACAEQACADAAAFQAAAFgDAFQgCAEgEACQgDADgFABQgFABgFAAQgGAAgIgDg");
	this.shape_5.setTransform(0.8,0.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AARAiIAAgkIgBgHIgCgHIgFgEQgDgCgFAAQgGAAgFAGQgFAGAAAKIAAAiIgNAAIAAgzIgBgHIAAgIIAMAAIABAGIAAAGIAEgGIAFgDIAGgDIAGgBQAGAAAFACQAFACADAEQADAEABAEQACAFAAAGIAAAog");
	this.shape_6.setTransform(-6.5,0.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgGAxIAAhBIAMAAIAABBgAgFgiQgDgDAAgDQAAgEADgCQACgCADgBQADABADACQADACAAAEQAAAEgDACQgDADgDgBQgDABgCgDg");
	this.shape_7.setTransform(-12.5,-1.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgDAmQgFgFAAgKIAAgjIgNAAIAAgLIANAAIAAgTIAMAAIAAATIASAAIAAALIgSAAIAAAhQAAAGACADQACACAFAAIAEAAIAEgBIAAALIgFABIgGAAQgJAAgEgFg");
	this.shape_8.setTransform(-20.6,-0.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgLAhQgGgDgFgFQgEgFgDgFQgDgHAAgIQAAgHADgGQACgGAFgGQAFgEAGgDQAGgCAGAAQAIAAAGACQAFACAFAFQAEAEACAHQACAGAAAIIAAABIAAACIgzAAQAAAFABADQACAEADADQADADAEACQADABAEAAQAGAAAFgDQAGgDACgEIAJAHQgFAHgHAEIgIACIgIABQgGAAgHgCgAAUgFIgCgHQgBgEgCgCQgCgDgEgCQgDgBgFAAQgDAAgEABQgEACgCADQgDACgCAEQgBADAAAEIAmAAIAAAAg");
	this.shape_9.setTransform(-27,0.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgNAwQgJgEgHgGQgHgIgEgJQgEgJAAgMQAAgLAEgKQAEgJAHgHIAHgGIAKgFQAKgDAJAAIAMAAIAKADQAKAEAFAGIgJAKQgEgFgIgDIgHgCIgIgBQgIAAgHADQgGADgGAGQgEAFgEAHQgCAIAAAHQAAAIACAHQAEAIAEAFQAGAGAHADQAGACAIAAIANAAIAKgEIAAgcIgVAAIAAgLIAjAAIAAAwQgIAEgJACIgUACQgKAAgLgEg");
	this.shape_10.setTransform(-36.9,-1.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ordernow, new cjs.Rectangle(-44.1,-11.9,85.8,21.2), null);


(lib.logokale = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeAfQgNgNAAgSQAAgRANgNQANgNARAAQASAAANANQANANAAARQAAASgNANQgNANgSAAQgRAAgNgNgAgYgYQgKAKAAAOQAAAQAKAKQAKAKAOAAQAPAAAKgKQAKgKAAgQQAAgOgKgKQgKgKgPAAQgOAAgKAKgAAMAZIgOgVIgFAAIAAAVIgJAAIAAgzIATAAQARAAAAAPQAAANgNABIAPAWgAgHgDIAGAAQANAAAAgIQAAgHgMAAIgHAAg");
	this.shape.setTransform(130.4,59.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjnEaQgUgDgIgEQgJgFAAgNQAAgKAGgHQAFgHAJAAIARAAQAKAAAFgLQADgKgBgXIAAl5QABgXgDgKQgFgLgKAAIgRAAQgJAAgFgHQgGgHAAgKQAAgNAJgFQAIgEAUgDQBegNBrAAQBNAAA1ASQA1ASAnAoQAlAlAVA5QATA4AABEQAABNgZA9QgZA+gwAlQglAegvAOQgxAOhEAAQhrAAhegNgAgvjrQgcAFgKALQgKAMAAAhIAAFjQAAAhAVALQANAHAnADQBNAEAshAQAqg/ABhwQAAhwgrg/Qgrg/hKAAIgdADg");
	this.shape_1.setTransform(62.2,30.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNBlQgFgDAAgHIAAiTQAAgKgMAAIgyAAQgKAAAAgPIABgNQACgIAHAAICfAAQAMAAAAASQAAASgLAAIgyAAQgMAAAAAKIABCTQAAAHgFADQgEACgKAAQgJAAgEgCg");
	this.shape_2.setTransform(81.2,88.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhMBmQgNAAAAgPIAAiuQAAgOANAAICbAAQAGAAADAFQACADAAAJQAAAKgCADQgDAGgHAAIh5AAQgIAAAAAJIAAAbQAAAKAKAAIBFAAQALAAAAASQAAAQgKAAIhFAAQgLAAAAALIAAAeQAAAKAKAAIB4AAQAKAAAAATQAAARgKAAg");
	this.shape_3.setTransform(52.4,88.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAxBgIhAhGQgLgJgTAAQgFAAgEAEQgDAFAAAGIAAA8QAAAMgVAAQgRAAAAgNIAAi0QAAgIAFgCQAEgCALAAQASAAAAAMIAAA3QAAANAJAAQALAAAFgDQAEgBAFgFIBJhDQANgLAMAMQAMALgKAKIhAA6QgJAIAJAJIBOBWQAIAIgGAFQgFAFgNAAQgTAAgHgIg");
	this.shape_4.setTransform(22.6,88.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAvBeIghgxQgFgJgKAAIgtAAQgEAAgDADQgDACgBAFIABAwQAAAHgKACIgPAAQgNAAAAgLIAAi6QAAgIAJAAIBrAAQAgAAAUASQAVAUgBAgQAAAXgOAPQgIAJgPAJQgHAIAEAFIAiAyQAFAHgFAFQgEAEgPAAQgRAAgFgJgAg5g4IAAAuQABAFAEADQAEACAFAAIA+AAQAQAAALgHQALgKAAgPQAAgRgLgJQgLgJgQAAIg+AAQgOAAAAALg");
	this.shape_5.setTransform(-11.1,88.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABCBgIgOgbQgCgHgHAAIhTAAQgJAAgEALIgMAXQgDAHgSAAQgWAAAFgMIBZi4QAFgKAKAAQALAAAFAJIBXC6QADAGgJAEQgGACgIAAQgPAAgDgIgAgEgdIgYAyQgDAIAIAAIAwAAQABAAABAAQAAgBABAAQABAAAAAAQAAgBABAAQACgCgCgDIgZgzQgBgDgEAAQgCAAgCADg");
	this.shape_6.setTransform(-44.3,88.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABZBlQgFgDAAgFIgOhrQgCgHgFAAQgDAAgDAEIgxA+QgEAFgFAAQgHAAgEgHIgtg7QgCgDgEAAQgFAAgBAHIgOBpQgCAKgTAAQgGAAgFgCQgGgDAAgGIAVixQACgJADgCQAEgFALAAQAKAAAFAIIA4BPQAFAIAEAAQAEAAAHgIIA7hQQAEgIALAAQAGAAADACQAEADACAJIAVC1QABAKgXAAQgFAAgFgCg");
	this.shape_7.setTransform(-78.1,88.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AipF/QhPhTAAiLQAAhZAghEQAghCA6gnQAZgTAmgTQAmgTAngOQAKgDgDgJQgCgKgNADQg7ALgrgSQgWgJgdgRQghgUgJgEQgvgWg6AZQgVAJgMgLQgLgLAGgXQAXhWBDg3QBKg9BQAXQA0APAlA0QAmA2AfALQATAGgBAPQAAAOgRADQgaAFgjgRQgggPgdgbQgfgcgvgCQgsgCgbAVQgLAIADAHQAEAHAKgDQAggHAdAGQAoAIAbAgQAkAoAuAPQA4ASAugfIAZgWQANgNAMAEQAPAEgBAUQgBAUgTAZQgiAsg+AeQhFAjgeAdQgwAwgTA9QgPAzAABQQAAByAqBAQAqBABKAAQBKAAArhCQAqhBAAhwQAAhfgXg4QgZg6g2gVQgbgKAFgTQAFgUAhgEQA3gGA8AsQBoBOAACjQAACOhPBVQhQBUiHAAQiDAAhPhUg");
	this.shape_8.setTransform(14.6,-54.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABnDxQhFg2gYheIgBgDQgCgLgHABQgGgBgCALIgBABQgYBghGA2QhIA2hoAAQh+AAhMhQQhMhRAAiFQAAiGBMhRQBLhQCAAAQBpAABHA2QBHA3AXBgQACALAGgBQAHAAACgLIABAAQAXhgBGg2QBHg2BoAAQB/AABNBPQBMBQAACGQAACHhMBRQhNBQiBAAQhmAAhHg2gACniqQgpA/AABtQAABtApA9QAoA+BIAAQBGAAApg/QAphAAAhrQAAhqgqhAQgpg/hHAAQhGAAgoA/gAmFiqQgoA/AABtQAABtAoA9QAoA+BIAAQBGAAApg/QAphAAAhrQAAhqgqhAQgpg/hHAAQhGAAgoA/g");
	this.shape_9.setTransform(-21,30.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ai5EbQgWAAgJgFQgIgFAAgOQAAgKAGgHQAHgHAJAAIARAAQAKAAAEgLQADgJAAgYIAAl7QAAgXgDgKQgCgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFvAAQAaAAAEAVIAMA7QAEAQgFAJQgFAJgMAAQgPAAgHgOQgEgFgFgNQgFgQgPgFQgNgEggAAIhtAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAFADAdAAIBFAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgTAAgEgXIAAgFQgCgNgIgDQgHgEgbAAIhFAAQgeAAgEAEQgIAFAAAZIAACLQAAAbACAGQAGALAMAAIATAAQAKAAAGAHQAGAHAAAKQAAAOgJAFQgIAFgYAAg");
	this.shape_10.setTransform(-98.4,30.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhTEbIgTgEQgIAAgKAJQgKAIgJAAQgLAAgGgHQgGgGgEgQIgVhUQgCgIAAgJQAAgMAHgIQAIgHAMAAQAMAAAJALIAMARQAWAfAhASQAiASAkAAQApAAAagVQAZgUAAgiQAAghgbgfQgbgdg/gsIhNg2QgSgPgTgWQgggmAAgzQAAg9ArgmQArgmBGAAQAlAAAjAIIAWAFIALACQAJAAALgIQAKgHAIAAQASAAAGAYIAUBcQABAEAAAIQAAAIgHAGQgHAGgKAAQgMAAgLgOQgNgVgHgIQgGgGgOgLQgjgbgtAAQgcAAgSAPQgRAQAAAaQAAAXAJALQAMASAbAWIApAdQAzAkAWARQAXASAUAUQAWAWAMAfQAMAeAAAhQAABJgyAtQgzAthUAAQgzAAglgNg");
	this.shape_11.setTransform(110.1,30.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ah+EYQgLgJgHgYIhJjYQgBgFgEAAQgFAAgBAFIhNDYQgKAagHAIQgNAIgQABQgTgBgKgIQgLgKgJgYIimm+QgKgZgHgIQgHgHgUgFQgOgBgFgGQgFgFAAgKQAAgXAdAAICvAAQAcAAAAAXQAAAMgHAEQgHAFgRABQgOACgGAEQgGAFAAALQAAAIADALIBzFGQACAFAFAAQAEgBACgFIA/i1QAIgZgHgYIglhuQgEgJgHgFQgGgEgPgEQgNgEgGgEQgFgGAAgJQAAgaAdAAICnAAQAdAAAAAXQAAATgcAFQgRABgFAFQgGAFAAALQAAALAIAZIBfEsQACAFAEAAQAFgBABgFIBdk6QAEgLAAgJQAAgTgdgDQgbgCAAgWQAAgMAHgGQAIgGARAAIElAAQAVAAAIAGQAIAFAAAOQAAAKgGAHQgGAHgJAAIgQAAQgLAAgFAKQgCAJAAAZIAABuQAAAdAFAHQAGAGAXAAIB0AAQAXAAAHgHQADgEAAgGIABgfIAAhoQAAgbgDgHQgFgKgKAAIgQAAQgKAAgHgHQgGgHAAgKQAAgOAIgFQAJgGAWAAICaAAQAWAAAJAGQAJAFAAAOQAAAKgHAHQgGAHgJAAIgSAAQgEAAgEADQgFAEgBADQgDAKAAAYIAAF8QAAAYADALQABADAFAEQAEACAEAAIASAAQAJAAAGAIQAHAGAAAKQAAAOgJAGQgIAEgXAAIiaAAQgWAAgIgEQgIgGAAgOQAAgKAGgGQAHgIAJAAIAQAAQAKABAFgKQADgIAAgbIAAh8IgBgdQAAgHgDgDQgHgIgXAAIh0AAQgXAAgGAHQgFAGAAAeIAACAQAAAZACAKQAFAKALgBIAQAAQAJAAAGAIQAGAGAAALQAAANgIAGQgIAEgVAAIiaAAQgWAAgJgEQgIgGAAgOQAAgKAGgGQAHgIAJAAIARAAQAEAAAFgCQAEgEABgDQADgIAAgbIAAl8QAAgwgkAEQgLABgHAJQgIAKgGAVIiHGzQgJAfgKAMQgLAKgTABQgTAAgLgKg");
	this.shape_12.setTransform(-74.6,-36.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AihEbQgWAAgIgFQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDACgEQADgIAAgXIAAmAQAAgZgDgHQgDgMgLAAIgRAAQgKABgGgHQgHgHAAgKQAAgOAJgFQAJgGAWAAICcAAQAWAAAJAGQAJAFAAAOQAAAKgGAHQgHAHgJgBIgSAAQgOAAgDAMQgDAFAAAbIAAFkQAAAdACAJQACAJAIAFQAGAFALABQALACAaAAIAwAAQAvAAAPggIAIgQQAIgPAPAAQAMgBAFAJQAFAJgEAQIgNBCQgEAVgaAAg");
	this.shape_13.setTransform(69.2,-37.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AjREWQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDABgEQAEgIAAgaIAAl7QAAgZgEgIQgBgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgKQAAgNAJgGQAIgFAWAAIFSAAQAZAAAFAVIAMA7QADAQgFAJQgFAIgMAAQgPAAgGgNQgDgCgGgQQgGgQgPgFQgMgEggAAIhQAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAEADAeAAIAmAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAIgOAAQgTAAgEgWIAAgFQgCgNgIgDQgHgEgbAAIgmAAQgeAAgEAEQgIAFAAAZIAABsQAAAiADALQADALAKAEQAPAFAiAAIBVAAQAvAAAPgfIAHgQQAIgQAPAAQAMAAAFAJQAFAJgDAQIgNBCQgFAVgaAAIlhAAQgWAAgIgFg");
	this.shape_14.setTransform(114.4,-37.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0C6E47").s().p("AqoZMQk7iEjyjzQjxjxiFk6QiKlGAAljQAAljCKlGQCFk6DxjzQDzjxE6iFQFFiKFjAAQFkAAFFCKQE7CFDxDxQDyDzCFE6QCKFGAAFjQAAFjiKFGQiFE6jyDxQjxDzk7CEQlFCKlkAAQljAAlFiKg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logokale, new cjs.Rectangle(-175,-175,350,350), null);


(lib.holidaytipsrecipesmore = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AgxA6QgWgXAAghQAAgjAWgXQAXgXAiAAQAdAAASARQARARAAAcQAAAKgDADQgCADgMAAIg6AAQgFAAgDgDQgDgCAAgEQAAgEADgCQADgDAFAAIAfAAIAIgBQAAAAABgBQAAAAAAgBQABAAAAgBQAAgBAAAAQAAgPgKgKQgKgLgOAAQgSAAgJARQgJAPAAAXQAAAXANASQAMARATAAQALAAAIgCQAHgDAIgFIAFgEQAIgHAEAAQAEAAACACQACADAAADQAAADgEAGQgDAFgHAFQgNALgNAFQgMAFgPAAQgfAAgWgWg");
	this.shape.setTransform(108,20.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AguBMQgHgCAAgHQAAgFAHgDIAEgCQAEgCACgFQACgFAAgMIgBgKIAAgNIAAgJQAAgbgBgJQgBgIgDgCIgIgDQgJgDAAgFQAAgDADgDQADgDAHgCIAUgHIAOgDQAHAAADAVIAAADIABABQAIgNAIgGQAJgHAJAAQAKAAAHAHQAGAGAAALQAAALgFAGQgFAGgJAAIgHgBIgHgFIgDgGQgCgEgCAAQgKAAgEAPQgEAOAAAuQAAANABAHQACAHAEACIAGACQAKADAAAGQAAAGgJACQgJADgUAAQgXAAgIgDg");
	this.shape_1.setTransform(94.3,20.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("Ag3A5QgWgWAAgiQAAgiAXgXQAXgXAhAAQAiAAAUAVQAWAWAAAiQAAAigXAYQgWAYghAAQgiAAgVgXgAgcgtQgKAMAAAVQAAAeANAUQANAUARAAQAQAAAJgMQAJgNAAgVQAAgdgNgUQgNgVgRAAQgQAAgIANg");
	this.shape_2.setTransform(79.5,20.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AA5BsQgIgDAAgGQAAgHAKgDIAGgEQADgCABgGQABgHAAgVIAAgIIAAhBIgBgmIgTAyQgtB2gKAAQgEAAgJgRQgJgQgWgyIghhMIgCA8IAAApIABAdQABAHACABIAHAEQAJADAAAHQAAAGgHADQgIADgTAAQgRAAgHgDQgIgDAAgHQAAgFAIgEQAJgEABgDQACgHACgoQACgnAAgwIAAgFQAAgQgBgFQgBgGgEgCIgHgDQgKgEAAgGQAAgGAHgDQAHgCAWAAIAWABIAGABQADACALAbIAJAWIAEALQAlBcADAAQADAAAOghQAOghASg2IADgJQAGgRAFgFQACgDAGgBIAVgBQAVAAAHACQAHADAAAGQAAAGgJADIgEACQgFADgCAGQgBAGAAAXIABBXQACAnABAGQABAEAHACIADABIAGAEQACACAAAEQAAAGgIADQgJADgZAAQgXAAgJgDg");
	this.shape_3.setTransform(56.9,16.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AhcBdQgdgWABgkQgBgTAKgQQAIgOAVgOIAAgBQgGgHgDgHQgEgIAAgIQAAgYASgPQARgQAdAAQASAAANAIQANAHAAAKQAAADgEADQgDACgDAAIgNgEQgKgEgJAAQgNAAgHAIQgHAIAAAOQAAAFABAFQACAEAFAEQADAEAHADIAJADIADABIABADQAAADgFAGQgGAHgFAAIgHgCIgKgEQgJAIgFAKQgEALAAAOQAAAdAUATQASATAeAAQAZAAAPgNQAPgNAAgUQAAgNgGgIQgGgIgLAAQgKAAgIAHQgGAGAAAKIAAADIAAABIgCABIgCAAQgGAAgDgEQgEgEAAgIQAAgWBEgfIAEgCQASgIAJgKQAJgJAAgLQAAgHgEgEQgEgDgIAAIgGAAIgGABQgDAAgCgCQgCgCAAgDQAAgHAIgFQAJgEANAAQARAAAJAJQAKAJAAAPQAAAUgRAPQgRAQgiANQAPAFAHALQAHAMAAAPQAAAMgFALQgEALgIAJQgPAQgUAHQgWAIgaAAQgvAAgcgWg");
	this.shape_4.setTransform(22.3,16.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AgLBQIgQgDIgFADIgFABIgDgBIgDgCQgFgFgFgMQgEgMAAgMQAAgFADgDQACgDAEAAQAHAAAIAMIAFAJQAFAHAIADQAIAEAIAAQAKAAAGgFQAGgGAAgIQAAgNgZgMIgJgFQgYgMgIgJQgIgKAAgOQAAgUANgNQAOgNAXAAIAKABIAKACIAIgDIAEgBQAIAAAHAMQAHAMAAAOQAAAFgCADQgCADgFAAQgDAAgEgDQgDgDgFgHQgGgKgGgDQgGgEgIAAQgIAAgGAFQgFAFAAAIQAAAHAFAFQAGAGASAJIACABQArAUAAAZQAAAWgRAOQgQAPgZAAg");
	this.shape_5.setTransform(-6.6,20.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AgxA6QgWgXAAghQAAgjAWgXQAXgXAiAAQAdAAASARQARARAAAcQAAAKgDADQgCADgMAAIg6AAQgFAAgDgDQgDgCAAgEQAAgEADgCQADgDAFAAIAfAAIAIgBQAAAAABgBQAAAAAAgBQABAAAAgBQAAgBAAAAQAAgPgKgKQgKgLgOAAQgSAAgJARQgJAPAAAXQAAAXANASQAMARATAAQALAAAIgCQAHgDAIgFIAFgEQAIgHAEAAQAEAAACACQACADAAADQAAADgEAGQgDAFgHAFQgNALgNAFQgMAFgPAAQgfAAgWgWg");
	this.shape_6.setTransform(-21.3,20.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AhKBpQgIgDAAgGQAAgFAHgDIAIgEQADgDABgMQABgMAAgmIAAgZQAAgpgBgMQgCgMgDgDIgHgCQgKgDABgFQgBgEADgDQADgCAGgCIAWgIQAKgCAFAAQAFAAACACQABACAAAGIAAAHIAAADIABABIAHgEIAGgEQAJgHAIgEQAIgDAKAAQAcAAASAVQATAVAAAhQAAAkgVAYQgUAXggAAQgNAAgEgDQgFgEgBgGQABgEACgCQACgDAFAAIAEABIAEABQARAAALgOQAKgPAAgXQAAgagLgQQgLgQgSAAQgPAAgJAJQgJAJAAAXIAABhIABAPQAAAGADADQACACAGACIAGABIAEADIABAFQAAAFgJADQgJACgWAAQgXAAgHgCg");
	this.shape_7.setTransform(-38.9,23);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AgbBuQgHgDAAgHQAAgFAHgDIAFgBQAEgCABgGQABgFAAgLIAAgLIAAgMIAAgQQAAgYgBgHQgBgHgDgCIgIgCQgJgDAAgFQABgEACgCQADgDAGgDIAYgHIAPgDQAFAAABADQACADAAAHIAAAJIAAAHIgCAmIAAABIAAAmQAAAOACAGQAAAGAEACIAGADQAHADABAFQAAAGgIADQgHACgUAAQgXAAgIgCgAgThNQgFgFgBgIQABgJAGgGQAIgGAKAAQAJAAAGAGQAHAFAAAJQAAAIgHAGQgHAGgKAAQgKAAgHgGg");
	this.shape_8.setTransform(-51.9,16.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006F46").s().p("AgwA6QgWgXAAghQAAgiAXgYQAXgXAiAAQAZAAASANQASANAAASQAAAHgFAFQgFAEgIAAQgIAAgEgEQgFgDgFgNQgFgLgGgEQgGgFgKAAQgQAAgKAOQgKANAAAYQAAAaAOARQAOARAVAAQAIAAAHgCQAHgCAFgEIAGgEQAIgHAFAAQADAAACACQACACAAADQAAAEgDAGQgDAFgFAEQgNALgMAFQgOAFgPAAQgfAAgWgWg");
	this.shape_9.setTransform(-64,20.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006F46").s().p("AgxA6QgWgXAAghQAAgjAWgXQAXgXAiAAQAdAAASARQARARAAAcQAAAKgDADQgCADgMAAIg6AAQgFAAgDgDQgDgCAAgEQAAgEADgCQADgDAFAAIAfAAIAIgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAgBAAAAQAAgPgKgKQgKgLgOAAQgSAAgJARQgJAPAAAXQAAAXANASQAMARATAAQALAAAIgCQAHgDAIgFIAFgEQAIgHAEAAQAEAAACACQACADAAADQAAADgEAGQgDAFgHAFQgNALgNAFQgMAFgPAAQgfAAgWgWg");
	this.shape_10.setTransform(-80.1,20.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006F46").s().p("AAhBMQgOgwgLgKQgKgKgQAAQgMAAAAgJQAAgKAKAAQAZAAAMgKQAMgKAAgVQAAgUgMgKQgNgLgXAAQgMAAgEACQgFABgBAFIgCAOIgBAeIAABEIABAuQABALADABIAHAEQAJADAAAHQAAAGgIADQgIADgZgBQgYABgIgDQgJgDAAgGQAAgHAKgDIAGgEQAEgDABgSIABhBIgBg7QgBgVgCgEQgCgCgIgDQgIgDAAgGQAAgGAFgCQAEgDAKAAIAiAAIAfgBIAXgBQAiAAASAPQARAOAAAcQAAATgLAPQgMAPgVAGIAAACQAQADAKAJQAJALAHAYIAEAQQAGAYAJAAIAFAAIAFgBQADAAACADQADACAAADQAAAHgJAFQgJAFgOgBQgfAAgKgkg");
	this.shape_11.setTransform(-98.8,17);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006F46").s().p("AgQAvQgBgBAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIADgGIADgEIAJgRQAEgIgBgDIgBgEIgFgCQgHgDgFgGQgDgGAAgIQAAgKAGgGQAHgHAJAAQAJAAAHAJQAHAJAAANQAAALgEAKQgEALgKAQIgIANQgDADgDAAQgEAAgDgBg");
	this.shape_12.setTransform(70.7,-5.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006F46").s().p("AgLBQIgQgDIgFADIgFABIgDgBIgDgCQgFgFgFgMQgEgMAAgMQAAgFADgDQACgDAEAAQAHAAAIAMIAFAJQAFAHAIADQAIAEAIAAQAKAAAGgFQAGgGAAgIQAAgNgZgMIgJgFQgYgMgIgJQgIgKAAgOQAAgUANgNQAOgNAXAAIAKABIAKACIAIgDIAEgBQAIAAAHAMQAHAMAAAOQAAAFgCADQgCADgFAAQgDAAgEgDQgDgDgFgHQgGgKgGgDQgGgEgIAAQgIAAgGAFQgFAFAAAIQAAAHAFAFQAGAGASAJIACABQArAUAAAZQAAAWgRAOQgQAPgZAAg");
	this.shape_13.setTransform(59.3,-13.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006F46").s().p("AhKBpQgIgDAAgGQAAgFAHgDIAHgEQAEgDABgMQABgMAAgmIAAgZQAAgpgBgMQgCgMgDgDIgHgCQgJgDAAgFQAAgEACgDQADgCAGgCIAWgIQAKgCAFAAQAFAAACACQACACAAAGIAAAHIAAADIAAABIAHgEIAFgEQAKgHAHgEQAKgDAIAAQAdAAASAVQASAVABAhQgBAkgUAYQgVAXgfAAQgNAAgEgDQgFgEAAgGQgBgEADgCQADgDAEAAIADABIAFABQARAAALgOQAKgPAAgXQAAgagLgQQgLgQgRAAQgQAAgJAJQgJAJAAAXIAABhIABAPQABAGABADQACACAHACIAGABIADADIACAFQAAAFgJADQgJACgWAAQgWAAgIgCg");
	this.shape_14.setTransform(43.3,-10.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006F46").s().p("AgbBuQgHgDAAgHQAAgFAHgDIAEgBQAEgCACgGQACgFgBgLIAAgLIAAgMIAAgQQAAgYgBgHQgBgHgDgCIgHgCQgKgDABgFQgBgEADgCQADgDAGgDIAYgHIAPgDQAFAAABADQACADAAAHIAAAJIgBAHIgBAmIAAABIAAAmQAAAOABAGQABAGAEACIAFADQAIADAAAFQABAGgIADQgIACgUAAQgWAAgIgCgAgShNQgHgFAAgIQAAgJAIgGQAHgGAKAAQAJAAAHAGQAGAFAAAJQAAAIgHAGQgHAGgKAAQgKAAgGgGg");
	this.shape_15.setTransform(30.2,-16.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006F46").s().p("AggBtQgJgDAAgGQAAgHAJgDQAJgDABgCQABgDABgZIAChIIgBgoIgCgZQAAgEgCgBQgDgCgHAAIgGAAQgKAAgHADQgFACgFAGIgEAKIgFALIgEAFQgDACgDAAQgEAAgDgEQgCgFAAgJQABgUAEgNQAFgMAHAAIACAAQAMACATAAIBZAAQATAAAMgCIABAAQAJAAAEAMQAFANgBAUQAAAJgCAEQgBAFgGAAIgEgCIgFgFIgEgLIgGgKQgEgGgFgCQgGgDgMAAIgGAAQgGAAgDACQgCABgBAEIgBAZIAAAoIABBIQABAZABADQABACAJADQAIADAAAHQAAAGgJADQgIADgYAAQgXAAgJgDg");
	this.shape_16.setTransform(16,-16.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006F46").s().p("AhGBmQgHgHgBgJQABgIAFgGQAFgFAIAAIAHABIAEADIAFAGQADAGAEAAQAHAAAIgLQAIgLAAgMQAAgNgLgZIgBgEIgZg1IgNgdQgEgGgJgEQgFgCgBgCQgDgCAAgDQABgIAHgCQAIgDAXAAQAXAAAHADQAIACAAAHIgBAEIgDADIgFADQgHACAAACIADAMIANAfIALAcQAFAIACAAQACAAADgIIAKgYIAMgeQADgLAAgEQAAgEgJgFQgIgFgBgEQABgFAGgCQAIgDARAAQATAAAGADQAHACgBAHQAAAFgJACIgFADQgJAEgKAaIgFAMIgTAxQgaBAgPASQgQAUgXAAQgLAAgHgGg");
	this.shape_17.setTransform(-10,-10.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006F46").s().p("AAbBIIgIgIIgGAEQgTAMgTAAQgWAAgOgNQgOgNAAgVQAAgYASgNQASgOAgAAQAHAAAEACQADADAAAFQABAJgKAAQgPAAgKAHQgJAHAAANQAAANAIAHQAIAHANAAQAPAAAGgGQAHgHAAgQIAAg6QgBgNgFgHQgGgIgKAAQgIAAgGAEQgGADgHAHIgDAEQgJAMgKAAQgHAAgEgEQgDgEAAgHQAAgOASgKQARgKAcAAQARAAAMAEQANAFAGAIQAEAGACAKQACAJAAAWIAAAxQAAAIACAFQABAEADABIAGABQAJADAAAFQAAAHgKAGQgKAGgOAAQgHAAgIgIg");
	this.shape_18.setTransform(-25.8,-13.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006F46").s().p("AhDBdQgSgVAAghQABglAUgXQAVgYAhAAIAKACQAFABADADQACAEAAAEQAAAIgKAAIgEAAIgEgBQgRAAgKAOQgKANAAAZQAAAZALARQALAQARAAQAPAAAJgJQAJgJAAgRIAAgqIAAhGQAAgLgBgEQgDgEgFgCIgFgCQgJgCAAgGQAAgEAEgDQADgDAMgEIARgFIAOgCQAFAAADADQACADAAAHIAAAIIgBBeIAABAQACAPACACIALADQAHACAAAGQABAHgXAHIgPAEIgMABQgEAAgCgCQgBgDgBgFIAAgHIAAgDIgBgBIgFADIgGAFQgKAHgHADQgKAEgIAAQgdAAgTgVg");
	this.shape_19.setTransform(-42.8,-16.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#006F46").s().p("AgaBuQgIgDAAgHQAAgFAIgDIADgBQAFgCABgGQABgFAAgLIAAgLIAAgMIAAgQQAAgYgBgHQgBgHgDgCIgHgCQgJgDAAgFQAAgEACgCQADgDAHgDIAXgHIAPgDQAEAAACADQACADAAAHIAAAJIgBAHIgBAmIAAABIAAAmQAAAOABAGQACAGADACIAFADQAJADgBAFQAAAGgHADQgHACgVAAQgWAAgHgCgAgShNQgHgFAAgIQAAgJAIgGQAGgGALAAQAJAAAHAGQAGAFAAAJQAAAIgHAGQgHAGgKAAQgKAAgGgGg");
	this.shape_20.setTransform(-56.8,-16.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#006F46").s().p("AgZBuQgHgCAAgHQAAgFAGgDIAHgEQADgCACgKIABgeIAAgYIgBgcIAAgMQAAgngBgLQgCgLgDgCIgJgDQgKgDAAgFQAAgEADgDQADgCALgEIAUgGIAPgCQAFAAACADQACADAAAHIAAAMQgCA3AAA2IABA1QABALACADIAJAEQAHADAAAGQAAAGgIACQgHADgUAAQgWAAgIgDg");
	this.shape_21.setTransform(-65.7,-16.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#006F46").s().p("Ag3A5QgWgWAAgiQAAgiAXgXQAXgXAhAAQAiAAAUAVQAWAWAAAiQAAAigXAYQgXAYggAAQgiAAgVgXgAgcgtQgKAMAAAVQAAAeANAUQANAUASAAQAPAAAJgMQAJgNAAgVQAAgdgNgUQgNgVgRAAQgQAAgIANg");
	this.shape_22.setTransform(-78.3,-13.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#006F46").s().p("AAiBsQgIgDAAgGQgBgHALgDIAGgEQACgCACgJIABgkIgBgWIgBgGQgBgDgIgBQgHgBgdAAIggABQgJABgCACIgCAFIAAALIAAANIABAkQABAJACACIAHAEQAJADAAAHQAAAGgIADQgIADgZAAQgYAAgIgDQgJgDAAgGQAAgHAJgDIAHgEQADgCACgTIABhBIgBg5QgBgXgCgDQgCgCgIgEQgIgDAAgGQAAgGAHgDQAGgCAdAAQAaAAAHACQAHADAAAGQAAAGgJAEIgHADQgDACgBAJIgBAuQAAAGAGACQAFACAXAAIAMAAIAhgBQAJgBADgCIABgDIABgGIAAgHIgBglQgCgIgCgCIgGgDQgLgEABgGQAAgGAHgDQAHgCAbAAQAcAAAGACQAHADAAAGQAAAGgJAEIgHADQgEACgBAVQgCAVAAApIACA7QABAXACADQACACAIADQAIAEAAAGQAAAGgJADQgIADgYAAQgYAAgJgDg");
	this.shape_23.setTransform(-98.6,-16.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaytipsrecipesmore, new cjs.Rectangle(-112.2,-36.9,230.5,73.9), null);


(lib.holidayhostingtips = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AgNBaIgSgEIgFAEIgFABIgEgBIgEgDQgFgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJAAQALAAAIgFQAGgGAAgJQAAgPgcgOIgKgFQgbgNgKgLQgJgLAAgRQAAgWAQgOQAPgOAZAAIAMAAIAMADIAIgEIAGgBQAIAAAIAOQAIANAAAPQAAAGgDAEQgDAEgFAAQgDAAgEgEQgEgDgGgIQgGgLgGgFQgIgDgJAAQgJgBgHAGQgFAFgBAKQAAAIAHAGQAGAGAUAKIACACQAxAWAAAcQAAAZgSAQQgTAQgcAAg");
	this.shape.setTransform(94.6,23);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AhTB2QgJgDAAgHQAAgGAHgDIAJgEQAEgEABgOQABgNAAgrIAAgcQAAgugBgOQgCgOgEgCIgIgDQgKgDAAgGQAAgEADgDQADgDAHgDIAYgIQAMgDAGAAQAFAAACADQACADAAAGIAAAIIAAADIABACIAHgFIAGgFQALgIAJgEQAKgEAKAAQAgAAAVAYQAUAXAAAmQAAAogXAbQgXAbgjAAQgPAAgFgEQgGgFAAgHQAAgDADgDQADgDAFAAIAEABIAGABQATAAAMgQQALgQAAgaQAAgegMgSQgNgSgTAAQgSAAgKAKQgLAKAAAaIAABtIABASQABAGACADQADACAHACIAHADIAEADIABAFQAAAGgKADQgKADgZAAQgZAAgIgDg");
	this.shape_1.setTransform(76.5,26.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AgeB8QgIgDAAgIQAAgGAIgDIAEgCQAFgCACgGQABgGAAgNIAAgMIAAgNIAAgSQAAgcgBgHQgCgIgDgCIgIgDQgLgDAAgGQAAgEAEgDQADgDAIgDIAagIIARgEQAEAAADAEQACADAAAIIAAAKIgBAIIgBArIAAABIgBArQAAAQACAHQABAHAEACIAGACQAKAEAAAGQgBAHgIADQgIACgXAAQgZAAgJgCgAgVhWQgHgGAAgJQAAgKAIgHQAIgHAMAAQAKAAAHAGQAIAHAAAJQAAAJgIAHQgIAHgLAAQgLAAgIgGg");
	this.shape_2.setTransform(61.8,19.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AgjB7QgKgDAAgIQAAgHAJgDQAJgEACgCQACgDABgdIABhRIgBgtIgBgcQAAgFgDgBQgDgCgHAAIgIAAQgMAAgGADQgHADgFAHIgFALIgGAMIgEAFQgDACgEAAQgFAAgCgEQgCgFgBgKQABgXAFgOQAFgOAIAAIACAAQAOACAVAAIBlAAQAVAAANgCIADAAQAIAAAFAOQAFAOABAXQAAAKgDAFQgCAEgFAAIgGgCIgGgFIgEgMIgGgLQgFgHgGgDQgIgDgLAAIgHAAQgIAAgCACQgDABgBAFIgCAcIAAAtIABBRQABAdACADQACACAJAEQAJADAAAHQABAIgKADQgKADgbAAQgaAAgJgDg");
	this.shape_3.setTransform(45.8,19.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AhABxQgVgOAAgTQAAgIAEgGQAFgGAKAAQAGAAAEAEQAEAFADAIQAEAMALAIQALAHAVAAQAWAAAPgJQAPgJABgNQgBgIgFgFQgGgEgKAAIgVABIgaACQgeAAgRgLQgRgKAAgOQAAgJAHgIQAGgIAMgHQgKgJgFgLQgFgLAAgOQAAgcAVgSQAVgTAhAAIARABIAbAGQAGAAAIgEQAHgDALgHIAFAFIACAGQABAHgGAHQgFAHgLAFIAGAOIACAOQgBAdgUASQgVARgiAAIgSgBIgQgEIgGAHIgBAGQAAAIAIAEQAIAEARAAIAZgCIAbgCQAZAAANAKQANAKgBASQAAAcgbASQgbASgpAAQggAAgXgNgAgchVQgJALAAARQAAASAJALQAIAKAPAAQANAAAKgKQAKgLAAgSQAAgRgKgLQgJgLgOAAQgNAAgKALg");
	this.shape_4.setTransform(16.6,25.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AAXBWQgIgDAAgGQAAgHAIgDIAHgDQAEgCABgIQACgIAAgSQAAg2gHgOQgHgOgSAAQgJAAgIAGQgIAFgFAKQgEAHgBANQgCANAAAiQAAARACAGQABAFAEACIAGADQAJADAAAHQAAAGgIADQgJADgWgBQgbABgIgDQgJgDAAgHQAAgHAJgCIAEgCQAEgDACgFQACgGAAgNIAAgNIAAgNIAAgRQAAgcgCgHQgBgJgDgCIgIgDQgLgDAAgGQAAgDADgDQAEgEAHgDIAZgIIASgDQAFAAACADQACADAAAFIAAALIAAACIABABIABgBIABAAIAEgDIAEgEQASgRAVAAQANgBALAGQAMAFAIAKQAIAJADANQADANAAAcIAAAWIAAAMIAAAKQAAAMACAFQACAFAEADIAEACQAJACAAAHQAAAHgIADQgIACgbAAQgYABgIgDg");
	this.shape_5.setTransform(-3.6,22.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AgeB8QgJgDAAgIQAAgGAJgDIAEgCQAEgCACgGQACgGABgNIgBgMIAAgNIAAgSQAAgcgCgHQAAgIgEgCIgIgDQgKgDAAgGQAAgEACgDQAEgDAHgDIAagIIASgEQAEAAACAEQACADAAAIIAAAKIAAAIIgBArIAAABIgBArQAAAQABAHQACAHAEACIAGACQAJAEAAAGQABAHgJADQgJACgWAAQgaAAgIgCgAgVhWQgHgGAAgJQAAgKAIgHQAIgHAMAAQAKAAAIAGQAHAHAAAJQAAAJgIAHQgIAHgMAAQgLAAgHgGg");
	this.shape_6.setTransform(-18.8,19.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AgIBoQgJgDgGgGQgGgFgDgKQgCgJAAgaIAAhcIgQAAIgFgBIgCgFIAAgEQAAgGASgPIAHgGIAHgGQASgQAHAAIAEACQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABIAAAgIAnAAQAEAAACACQABABAAAFIAAAEQAAAFgBACQgCACgEAAIgkAAIgDABIgBAEIAABVQAAAXAEAFQAEAGAKAAQAGAAAIgDIAMgDQAEAAACADQADACAAADQAAAKgPAJQgPAJgSAAQgKAAgIgDg");
	this.shape_7.setTransform(-29.7,21.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AgNBaIgSgEIgFAEIgGABIgDgBIgEgDQgFgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJAAQALAAAIgFQAGgGAAgJQAAgPgcgOIgKgFQgbgNgKgLQgJgLAAgRQAAgWAQgOQAPgOAZAAIAMAAIAMADIAIgEIAGgBQAIAAAIAOQAIANAAAPQAAAGgDAEQgCAEgGAAQgEAAgDgEQgEgDgGgIQgGgLgGgFQgIgDgJAAQgJgBgHAGQgFAFAAAKQgBAIAHAGQAGAGAUAKIADACQAwAWAAAcQAAAZgSAQQgTAQgcAAg");
	this.shape_8.setTransform(-43.4,23);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006F46").s().p("Ag+BBQgZgaAAgmQAAgmAagaQAagaAmAAQAlAAAYAYQAYAYAAAmQAAAngaAbQgZAbglAAQgmAAgYgZgAgggzQgLAOAAAXQAAAiAPAXQAOAXAUAAQARAAALgOQAKgPAAgXQAAghgOgXQgPgXgUAAQgRAAgKAOg");
	this.shape_9.setTransform(-60.5,23);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006F46").s().p("AAmB6QgJgDAAgIQAAgHALgEIAHgEQADgCABgLIACgoIgBgYIgBgHQgCgDgIgCQgJgBggAAIgkABQgKABgDACIgCAGIgBAMIAAAPIACAoQABALADACIAHAEQALAEAAAHQAAAIgKADQgJADgcAAQgbAAgJgDQgKgDAAgIQAAgHALgEIAHgEQAEgCACgWQABgWAAgzIgBhBQgCgagCgDQgCgCgJgEQgJgEAAgHQAAgGAIgDQAHgDAgAAQAeAAAIADQAIADAAAGQAAAHgLAEIgHAEQgEADgBAKIgBAzQAAAHAHADQAGACAZAAIAOAAIAkgBQALgBADgDIACgDIABgHIAAgHIgCgrQgBgJgDgCIgHgEQgLgEAAgHQAAgGAIgDQAIgDAeAAQAfAAAIADQAIACAAAHQAAAHgLAEIgIAEQgDADgCAXQgCAYAAAuIACBCQABAaADAEQABACAJAEQAKADAAAHQAAAIgKADQgKADgbAAQgbAAgKgDg");
	this.shape_10.setTransform(-83.3,19.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006F46").s().p("AhPByQgIgHAAgLQAAgIAGgHQAGgGAIAAIAIABIAFAEIAFAHQAEAHAEAAQAJAAAJgNQAJgNAAgNQAAgPgMgcIgCgEIgcg8IgQghQgDgGgKgFIAAAAQgGgCgCgCQgCgDAAgEQAAgHAJgDQAJgDAZAAQAaAAAIADQAIACAAAHIgBAGIgDADIgGADQgHACAAADIAEANIAOAjIANAgQAFAJACAAQACAAAEgJIALgbIANgiQAEgMAAgFQAAgFgKgFQgKgGAAgEQAAgGAIgDQAIgCAUAAQAVAAAHADQAHACAAAHQAAAHgKACIgHACQgKAGgLAdIgFANIgWA3QgcBIgSAWQgSAVgZAAQgNAAgIgHg");
	this.shape_11.setTransform(16.3,-11.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006F46").s().p("AAfBRIgJgJIgIAEQgVAOgVAAQgZAAgQgOQgPgPAAgYQAAgbATgPQAVgPAkAAQAIAAAFACQAEADAAAGQAAAKgMAAQgRAAgKAIQgKAIAAAPQgBAOAKAIQAIAIAQAAQAQAAAHgHQAHgIAAgSIAAhBQAAgPgHgIQgGgIgMAAQgIAAgHADQgIAEgGAIIgEAEQgLAOgLAAQgHAAgEgFQgEgEAAgIQAAgQAUgLQAUgLAfAAQATAAAOAFQANAFAIAKQAFAGACALQACAKAAAZIAAA3QAAAKACAFQACAEADABIAGACQAKADABAGQAAAIgMAHQgMAGgPAAQgHAAgJgJg");
	this.shape_12.setTransform(-1.4,-15);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006F46").s().p("AhLBoQgUgXAAglQAAgqAXgaQAXgbAlABIAMABQAFACADAEQADADAAAEQAAAKgLAAIgFgBIgEAAQgTAAgMAQQgLAOAAAcQAAAdAMASQANASATAAQASABAKgLQAKgKAAgTIAAgvIAAhPQAAgMgDgFQgCgEgGgDIgFgBQgLgEAAgFQAAgFAEgEQAFgDANgFIATgFIAQgCQAGAAADAEQACACAAAJIAAAIIgCBqIABBJQABAQADACIAMAEQAJACAAAGQAAAIgZAIIgRAFIgNACQgFAAgCgEQgCgCAAgGIAAgJIgBgDIgBgBIgFAEIgIAFQgKAJgJADQgKAEgKAAQghAAgUgYg");
	this.shape_13.setTransform(-20.5,-18.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006F46").s().p("AgeB8QgJgDAAgIQAAgGAJgDIAEgCQAEgCACgGQACgGABgNIgBgMIAAgNIAAgSQAAgcgCgHQAAgIgEgCIgIgDQgKgDAAgGQAAgEACgDQAEgDAHgDIAagIIASgEQAEAAACAEQACADAAAIIAAAKIAAAIIgBArIAAABIgBArQAAAQABAHQACAHAEACIAGACQAJAEAAAGQABAHgJADQgJACgWAAQgaAAgIgCgAgVhWQgHgGAAgJQAAgKAIgHQAIgHAMAAQAKAAAIAGQAHAHAAAJQAAAJgIAHQgIAHgMAAQgLAAgHgGg");
	this.shape_14.setTransform(-36.3,-19);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006F46").s().p("AgcB9QgJgEAAgHQAAgFAHgDIAJgGQADgCABgKIABgjIAAgbIAAggIAAgNQAAgrgBgNQgCgNgEgBIgKgFQgLgCAAgHQAAgEADgCQAEgDAMgFIAXgHIARgCQAFAAACADQADADAAAJIgBANQgCA+AAA+IABA6QABANADADIAKAFQAIAEAAAGQAAAGgJAEQgIACgXAAQgZAAgIgCg");
	this.shape_15.setTransform(-46.3,-19);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006F46").s().p("Ag+BBQgZgaAAgmQAAgmAagaQAagaAmAAQAlAAAYAYQAYAYAAAmQAAAngaAbQgZAbglAAQgmAAgYgZgAgggzQgLAOAAAXQAAAiAPAXQAOAXAUAAQARAAALgOQAKgPAAgXQAAghgOgXQgPgXgUAAQgRAAgKAOg");
	this.shape_16.setTransform(-60.5,-15);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006F46").s().p("AAmB6QgJgDAAgIQAAgHALgEIAHgEQADgCABgLIACgoIgBgYIgBgHQgCgDgIgCQgJgBggAAIgkABQgKABgDACIgCAGIgBAMIAAAPIACAoQABALADACIAHAEQALAEAAAHQAAAIgKADQgJADgcAAQgbAAgJgDQgKgDAAgIQAAgHALgEIAHgEQAEgCACgWQABgWAAgzIgBhBQgCgagCgDQgCgCgJgEQgJgEAAgHQAAgGAIgDQAHgDAgAAQAeAAAIADQAIADAAAGQAAAHgLAEIgHAEQgEADgBAKIgBAzQAAAHAHADQAGACAZAAIAOAAIAkgBQALgBADgDIACgDIABgHIAAgHIgCgrQgBgJgDgCIgHgEQgLgEAAgHQAAgGAIgDQAIgDAeAAQAfAAAIADQAIACAAAHQAAAHgLAEIgIAEQgDADgCAXQgCAYAAAuIACBCQABAaADAEQABACAJAEQAKADAAAHQAAAIgKADQgKADgbAAQgbAAgKgDg");
	this.shape_17.setTransform(-83.3,-18.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidayhostingtips, new cjs.Rectangle(-98.3,-41.5,202.7,83.1), null);


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("A2aygMAs1AAAMAAAAlBMgs1AAAg");
	this.shape.setTransform(0,0,1.042,1.051);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-150.5,-125.5,301,251), null);


(lib.getthepartystarted = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AgkAsIgEgBQAAAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIAAhPQAAAAAAAAQAAgBAAAAQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAIAhAAIAIABIAJACQAJADAGAGQAHAGADAIIADAJIABAIQAAAKgEAIIgEAHIgGAHIgHAFIgIAEQgJADgIAAgAgXgaQgBAAAAABQAAAAAAABQgBAAAAABQAAAAAAAAIAAAwQAAAAAAABQAAAAABAAQAAABAAAAQAAAAABABIADABIAQAAQAFAAAGgCQAFgDAFgDQAEgDACgGQADgFAAgHQAAgFgDgGQgCgFgEgEQgFgDgFgCQgGgCgFgBIgQAAQAAAAgBABQAAAAgBAAQAAAAAAAAQgBABAAAAg");
	this.shape.setTransform(80.1,-0.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AgdAsIgDgBIgCgCIAAhRQAAAAABAAQAAgBAAAAQAAAAAAAAQABgBAAAAIADgBIA9AAIACACIABACIAAAEIAAACIgBADIgCACIgtAAIgDACIgBADIAAALIABAEIADABIAdAAIABABIABACIABAEIAAACQAAAEgDAAIgcAAIgEACQAAAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAMIABAEQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABAAIAtAAQACABAAADIABAEIgBADIgBADIgCABg");
	this.shape_1.setTransform(70.8,-0.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAAAQgBAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQAAgBgBAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_2.setTransform(62.5,-0.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AAWAtIgCgBIgCgBIgBgBIgPgXIgCgDIgEgBIgKAAIgEABIgCADIABAWQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAAAAAIgDABIgEABIgDAAIgEgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBgBAAAAIAAhQQAAgBABAAQAAAAAAgBQAAAAAAAAQABgBAAAAIADgBIAkAAQAHAAAFACQAHADADADQAFAEACAGQACAFAAAHQAAAIgDAEQgCAEgEADIgFAFQgBAAgBABQAAAAgBAAQAAABAAAAQgBABAAAAIAAACIAEAFIAFAHIAFAHIACAFIgBACIgDACIgEABIgCABgAgSgbQAAAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAIAAAUQAAAAABABQAAAAAAABQAAAAABABQAAAAAAABIAFAAIARAAIAGAAIAFgDQADgBABgDQACgDAAgEQgBgHgFgEIgFgCIgGgBIgRAAIgFABg");
	this.shape_3.setTransform(54.7,-0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AAjAsIgDAAIgEAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBgBAAIgFgMIgBgCIgDgBIgdAAIgBABIgBAAIgBABIgBABIgFAMIgCACIgCAAIgDABIgCAAIgCAAIgDAAIgCgBQgBAAAAAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAlhSIACgCIACgBIAEAAQAAABABAAQAAAAABAAQAAABAAAAQABABAAAAIAjBSIAAABIgBABIgDABgAAAgNIgBABIgBACIgCAEIgCAFIgCAFIgCADIAAACIAAACIACABIARAAIACgBIABgCIgCgDIgDgHIgDgHIgCgEIgCgBg");
	this.shape_4.setTransform(45.5,-0.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAAAQgBAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQAAgBgBAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_5.setTransform(37.6,-0.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AgTAqQgKgDgHgHIgBgCIAAgBIABgDIADgDIADgCIADgBIAEABIAGAEIAHAEQAEABAGAAIAGAAIAHgCIAFgEQACgDAAgEQAAgDgCgCQgDgDgDgBIgKgBIgJgCIgKgCQgFgBgEgCQgEgDgDgEQgCgFAAgGQAAgHADgFQAEgFAFgEQAFgDAHgBIALgCIAJABIAIACIAJADIAHAFIAAACIABABIgBADIgDADIgDACIgEABIgCAAQgFgEgFgDQgFgCgGAAIgGAAIgGACIgEAEQgCACAAAEQAAAFAEACIAKADIANACQAHABAHACQAGADAEADQAFAFAAAJQgBAIgDAGQgEAFgFAEQgGADgHACIgMACQgKAAgJgEg");
	this.shape_6.setTransform(29.7,-0.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AgBAuIgBAAIgCAAIgDgCIAAgCIAAgeIgBgGIgCgEIgagnIAAgBIABgCIADgCIAEgCIACgBIAEABIACACIARAdIACABIABAAIACAAIACgBIASgdIACgCIACgBIADAAIAEACIACACIABACIAAABIAAABIgZAnIgDAFIAAADIAAABIAAAfQgCADgCABg");
	this.shape_7.setTransform(17.7,-0.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_8.setTransform(10.1,-0.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006F46").s().p("AAWAtIgCgBIgCgBIgBgBIgPgXIgCgDIgEgBIgLAAIgDABIgBADIAAAWQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAAAAAIgEABIgDABIgDAAIgEgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBgBAAIAAhQQABgBAAAAQAAAAAAgBQAAAAAAAAQABgBAAAAIACgBIAlAAQAHAAAFACQAGADAEADQAFAEACAGQADAFgBAHQAAAIgCAEQgDAEgEADIgGAFQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAAAIAAACIAEAFIAFAHIAFAHIACAFIgBACIgDACIgEABIgCABgAgSgbQAAAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAAUQAAAAAAABQAAAAAAABQAAAAABABQAAAAAAABIAEAAIASAAIAGAAIAGgDQACgBABgDQABgDAAgEQAAgHgEgEIgGgCIgGgBIgSAAIgEABg");
	this.shape_9.setTransform(2.3,-0.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006F46").s().p("AAjAsIgDAAIgEAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBgBAAIgFgMIgBgCIgDgBIgdAAIgBABIgBAAIgBABIgBABIgFAMIgCACIgCAAIgDABIgCAAIgCAAIgDAAIgCgBQgBAAAAAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAlhSIACgCIACgBIAEAAQAAABABAAQAAAAABAAQAAABAAAAQABABAAAAIAjBSIAAABIgBABIgDABgAAAgNIgBABIgBACIgCAEIgCAFIgCAFIgCADIAAACIAAACIACABIARAAIACgBIABgCIgCgDIgDgHIgDgHIgCgEIgCgBg");
	this.shape_10.setTransform(-6.9,-0.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006F46").s().p("AgeAtQgEAAgCgEIAAhSIACgCIACgBIAmAAQAGAAAFACQAGACAEAEQAFADACAFQADAFAAAHIgBAEIgBAEQgDAIgGAEQgGAEgHABQgHABgHAAIgPAAIgBAAIgBABIgCADIAAAcIgCACIgCAAIgDABgAgSgbQgBABAAAAQAAAAAAABQgBAAAAABQAAAAAAABIAAAOIACADIACABIAWAAIAFgBIAEgCQADgBABgDIABgFIgBgFIgDgDIgFgDIgEAAIgWAAQgBAAAAAAQgBAAAAAAQAAAAgBABQAAAAAAAAg");
	this.shape_11.setTransform(-15,-0.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006F46").s().p("AgdAsIgDgBIgBgCIAAhRQAAAAAAAAQAAgBAAAAQAAAAAAAAQABgBAAAAIACgBIA+AAIABACIABACIAAAEIAAACIAAADIgCACIgtAAIgDACIgBADIAAALIABAEIADABIAdAAIABABIABACIABAEIAAACQAAAEgEAAIgbAAIgDACQgBAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAMIABAEQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABAAIAtAAQACABAAADIAAAEIAAADIgBADIgCABg");
	this.shape_12.setTransform(-27.5,-0.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006F46").s().p("AAbAtIgEAAIgDgCIAAggQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQgBgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgcAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgBABAAAAQgBABAAAAQAAAAAAABQgBAAAAABQAAAAAAABIAAAeQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBABIgCAAIgEAAIgDAAIgDgBIgCgCIAAhTIACgCIADgBIADAAIADAAQAEAAABADIAAAcIABAEIADABIAeAAIAEgBQAAgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAAgcQACgDADAAIAFAAIAEABIACACIAABTQgBADgDAAg");
	this.shape_13.setTransform(-36.9,-0.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006F46").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAAAQgBAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQAAgBgBAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_14.setTransform(-45.4,-0.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006F46").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAAAQgBAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQAAgBgBAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_15.setTransform(-56.4,-0.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006F46").s().p("AgdAsIgDgBIgBgCIAAhRQAAAAAAAAQAAgBAAAAQAAAAAAAAQABgBAAAAIACgBIA9AAIACACIABACIAAAEIAAACIAAADIgDACIgsAAIgDACIgBADIAAALIABAEIADABIAdAAIABABIACACIAAAEIAAACQAAAEgEAAIgcAAIgCACQgBAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAMIABAEQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABAAIAsAAQADABAAADIAAAEIAAADIgBADIgCABg");
	this.shape_16.setTransform(-63.9,-0.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006F46").s().p("AgHAtIgIgDIgIgDIgIgGIgFgHIgFgHQgDgJAAgKIAAgIIADgJQAEgJAGgGIAIgFIAIgEIAIgDIAJgBQAFAAAFACIAKACQAJAFAHAHIAAACIgBADIgDADIgDACIgDACIgEgCIgFgEIgHgFQgEgCgGAAQgFABgGACQgFACgEAEQgFAFgCAFQgCAGAAAFQAAAGACAGQACAFAFAEQAEAEAFADQAGACAFABIAGgBIAGgBIAGgEQACgBACgDIAAgBIgBgDIgDgBIgQAAIgCgBIgBgDIAAgDIAAgDIAAgDQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAIAlAAIABABIABABQACADAAAFIAAADIgBAEIgHAMQgEAFgGAEQgFADgHACQgGACgHAAIgJgBg");
	this.shape_17.setTransform(-73.9,-0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.getthepartystarted, new cjs.Rectangle(-80.9,-8.4,167.9,16.9), null);


(lib.fourteenrectanglevideo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("AnZCXQg+AAgtgsQgsgsAAg/IAAAAQAAg+AsgsQAtgsA+AAIOzAAQA+AAAsAsQAtAsAAA+IAAAAQAAA/gtAsQgsAsg+AAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteenrectanglevideo, new cjs.Rectangle(-62.5,-15.1,125,30.3), null);


(lib.fourteenrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AnZCXQg+AAgtgsQgsgsAAg/IAAAAQAAg+AsgsQAtgsA+AAIOzAAQA+AAAsAsQAtAsAAA+IAAAAQAAA/gtAsQgsAsg+AAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteenrectangle, new cjs.Rectangle(-62.5,-15.1,125,30.3), null);


(lib.cookietopleft_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.cookietopleft();
	this.instance.parent = this;
	this.instance.setTransform(-65.5,-34.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.cookietopleft_1, new cjs.Rectangle(-65.5,-34.5,131,69), null);


(lib.cookiebottomleft_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.cookiebottomleft();
	this.instance.parent = this;
	this.instance.setTransform(-34.5,-29.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.cookiebottomleft_1, new cjs.Rectangle(-34.5,-29.5,69,59), null);


(lib.cookie_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.cookie();
	this.instance.parent = this;
	this.instance.setTransform(-42.5,-70);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.cookie_1, new cjs.Rectangle(-42.5,-70,85,140), null);


(lib.cbr = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.cookiebottomright();
	this.instance.parent = this;
	this.instance.setTransform(-101,-53);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.cbr, new cjs.Rectangle(-101,-53,202,106), null);


(lib.fourteenrollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_1 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(1).call(this.frame_1).wait(10).call(this.frame_11).wait(12).call(this.frame_23).wait(7));

	// cta-rectangle
	this.instance = new lib.fourteenrectanglevideo();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-62.5,-15.1,125,30.3);


(lib.buttonmain = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.square("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0.1,0);
	this.instance._off = true;
	this.instance.filters = [new cjs.ColorFilter(0, 0, 0, 1, 0, 110, 71, 0)];
	this.instance.cache(-153,-128,306,256);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


// stage content:
(lib.squarefourteenupdatedcta = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_46 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_198 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(46).call(this.frame_46).wait(152).call(this.frame_198).wait(8));

	// button
	this.btn_main = new lib.buttonmain();
	this.btn_main.parent = this;
	this.btn_main.setTransform(149.5,124.2);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.buttonmain(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(206));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(206));

	// white-square
	this.instance_1 = new lib.whitesquare();
	this.instance_1.parent = this;
	this.instance_1.setTransform(153,126.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:0},9).wait(197));

	// kale-logo
	this.instance_2 = new lib.logokale();
	this.instance_2.parent = this;
	this.instance_2.setTransform(250.8,32.8,0.003,0.003);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({scaleX:0.24,scaleY:0.24,alpha:1},6,cjs.Ease.get(1)).to({regY:0.2,scaleX:0.22,scaleY:0.22},7,cjs.Ease.get(1)).wait(184));

	// order-now-mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AoMOwIAAk+IVwAAIAAE+g");
	mask.setTransform(86.8,94.4);

	// order-now
	this.instance_3 = new lib.ordernow();
	this.instance_3.parent = this;
	this.instance_3.setTransform(143.7,184.5);
	this.instance_3.alpha = 0;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(46).to({x:-150.9,y:172.6},0).to({x:83.4,alpha:1},10,cjs.Ease.get(1)).to({x:78.4},8,cjs.Ease.get(1)).wait(142));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("A3fU6MAAAgpUMAxeAAAMAAAApUg");
	mask_1.setTransform(166.3,133.8);

	// cta-rollover
	this.cta_rollover = new lib.fourteenrollover();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(76.6,172.3);
	this.cta_rollover.alpha = 0;

	var maskedShapeInstanceList = [this.cta_rollover];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(46).to({x:-150.9},0).to({x:83.4,alpha:1},10,cjs.Ease.get(1)).to({x:78.4},8,cjs.Ease.get(1)).wait(142));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("A3fU6MAAAgpUMAxeAAAMAAAApUg");
	mask_2.setTransform(166.3,133.8);

	// cta-rectangle
	this.instance_4 = new lib.fourteenrectangle();
	this.instance_4.parent = this;
	this.instance_4.setTransform(76.6,172.5);
	this.instance_4.alpha = 0;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(46).to({x:-150.9},0).to({x:83.4,alpha:1},10,cjs.Ease.get(1)).to({x:78.4},8,cjs.Ease.get(1)).wait(142));

	// mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	mask_3.graphics.p("A3fU6MAAAgpUMAxeAAAMAAAApUg");
	mask_3.setTransform(166.3,133.8);

	// eyebrow
	this.instance_5 = new lib.getthepartystarted();
	this.instance_5.parent = this;
	this.instance_5.setTransform(96,71.8);
	this.instance_5.alpha = 0;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(167).to({x:-154},0).to({x:106,alpha:1},10,cjs.Ease.get(1)).to({x:96},6,cjs.Ease.get(1)).wait(23));

	// mask (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	mask_4.graphics.p("A3fU6MAAAgpUMAxeAAAMAAAApUg");
	mask_4.setTransform(166.3,133.8);

	// holiday-tips-recipes-more
	this.instance_6 = new lib.holidaytipsrecipesmore();
	this.instance_6.parent = this;
	this.instance_6.setTransform(126.3,115.7);
	this.instance_6.alpha = 0;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(177).to({x:-123.7},0).to({x:136.3,alpha:1},10,cjs.Ease.get(1)).to({x:126.3},6,cjs.Ease.get(1)).wait(13));

	// mask (mask)
	var mask_5 = new cjs.Shape();
	mask_5._off = true;
	mask_5.graphics.p("A3fU6MAAAgpUMAxeAAAMAAAApUg");
	mask_5.setTransform(166.3,133.8);

	// party-ready-recipes
	this.instance_7 = new lib.partyreadyrecipes();
	this.instance_7.parent = this;
	this.instance_7.setTransform(109.6,106.3);
	this.instance_7.alpha = 0;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_5;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(36).to({x:-120.4},0).to({x:116.6,alpha:1},10,cjs.Ease.get(1)).to({x:109.6},6,cjs.Ease.get(1)).wait(30).to({alpha:0},5).wait(119));

	// sweet-inspiration
	this.instance_8 = new lib.sweetinspiration();
	this.instance_8.parent = this;
	this.instance_8.setTransform(98.4,106.3);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(122).to({alpha:1},10).wait(30).to({alpha:0},5).wait(39));

	// holiday-hosting tips
	this.instance_9 = new lib.holidayhostingtips();
	this.instance_9.parent = this;
	this.instance_9.setTransform(112.4,106.3);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(82).to({alpha:1},10).wait(30).to({alpha:0},5).wait(79));

	// cookie-top-left
	this.instance_10 = new lib.cookietopleft_1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(65.5,34.5);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(29).to({alpha:1},10).wait(167));

	// cookie-bottom-left
	this.instance_11 = new lib.cookiebottomleft_1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(34.5,220.5);
	this.instance_11.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(14).to({alpha:1},10).wait(182));

	// cbr
	this.instance_12 = new lib.cbr();
	this.instance_12.parent = this;
	this.instance_12.setTransform(199,197);
	this.instance_12.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(19).to({alpha:1},10).wait(177));

	// cookie-top-right
	this.instance_13 = new lib.cookie_1();
	this.instance_13.parent = this;
	this.instance_13.setTransform(257.5,70);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(24).to({alpha:1},10).wait(172));

	// table-tan
	this.instance_14 = new lib.table_1();
	this.instance_14.parent = this;
	this.instance_14.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(206));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(144.1,118.1,318,266);
// library properties:
lib.properties = {
	id: '92879F2740E34FB9890B82961B713FEA',
	width: 300,
	height: 250,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/index_atlas_.jpg?1511107436021", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['92879F2740E34FB9890B82961B713FEA'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;